{{- if .Values.akv.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "device-app.fullname" . }}-akv
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "false"
    usePodIdentity: "false"
    keyvaultName: "{{ .Values.akv.name }}"
    tenantId: "{{ .Values.akv.tenantId }}"
    # objects format:  array -> converted into the expected string
    objects: |
      array:
{{- range .Values.akv.objects }}
        - |
          objectName: "{{ .objectName }}"
          objectType: "{{ .objectType }}"
{{- if .objectVersion }}
          objectVersion: "{{ .objectVersion }}"
{{- end }}
{{- end }}
{{- if eq .Values.akv.auth.mode "workloadIdentity" }}
    # With Azure Workload Identity, auth is handled via projected token and SA annotations.
    # No clientId/secret here; ensure ServiceAccount is annotated appropriately.
    {{- if .Values.akv.auth.workloadIdentity.userAssignedIdentityClientId }}
    userAssignedIdentityID: "{{ .Values.akv.auth.workloadIdentity.userAssignedIdentityClientId }}"
    {{- end }}
{{- else if eq .Values.akv.auth.mode "servicePrincipal" }}
    clientId: "{{ .Values.akv.auth.servicePrincipal.clientId }}"
    {{- $sp := .Values.akv.auth.servicePrincipal }}
    {{- $clientSecret := "" }}
    {{- if $sp.clientSecretValue }}
    {{- $clientSecret = $sp.clientSecretValue }}
    {{- else if $sp.clientSecretSecretRef.name }}
    {{- $secretObj := lookup "v1" "Secret" .Release.Namespace $sp.clientSecretSecretRef.name }}
    {{- if not $secretObj }}
    {{- fail (printf "servicePrincipal.clientSecretSecretRef.name %q not found in namespace %q" $sp.clientSecretSecretRef.name .Release.Namespace) }}
    {{- end }}
    {{- $secretKey := default "clientSecret" $sp.clientSecretSecretRef.key }}
    {{- $clientSecretB64 := index $secretObj.data $secretKey }}
    {{- if not $clientSecretB64 }}
    {{- fail (printf "key %q not present in Secret %q" $secretKey $sp.clientSecretSecretRef.name) }}
    {{- end }}
    {{- $clientSecret = $clientSecretB64 | b64dec }}
    {{- end }}
    {{- if not $clientSecret }}
    {{- fail "Azure Key Vault service principal mode requires a client secret via clientSecretValue or clientSecretSecretRef" }}
    {{- end }}
    clientSecret: "{{ $clientSecret }}"
{{- end }}
  {{- if .Values.akv.syncK8sSecret.enabled }}
  secretObjects:
  - secretName: {{ .Values.akv.syncK8sSecret.name }}
    type: {{ .Values.akv.syncK8sSecret.type | default "Opaque" }}
    data:
{{- range .Values.akv.syncK8sSecret.mappings }}
    - key: {{ .key }}
      objectName: {{ .objectName }}
{{- end }}
  {{- end }}
{{- end }}
